### ISSUE TITLE
Can't resolve all parameters for CordovaOauth: (?).

### ISSUE THREAD

**Issue by melkir** [nraboy/ng2-cordova-oauth#21]
Hi,
I tried to use your plugin with the lastest version of Ionic 2 and there's some unmet dependency.
Also when I'm trying to login the user with Google I get this message : 
`ORIGINAL STACKTRACE:
Error: Can't resolve all parameters for CordovaOauth: (?).
    at new BaseException (http://192.168.0.24:8100/build/js/app.bundle.js:2892:23)
    at CompileMetadataResolver.getDependenciesMetadata (http://192.168.0.24:8100/build/js/app.bundle.js:14580:19)
    at CompileMetadataResolver.getTypeMetadata (http://192.168.0.24:8100/build/js/app.bundle.js:14461:26)
    at http://192.168.0.24:8100/build/js/app.bundle.js:14615:30
    at Array.map (native)
    at CompileMetadataResolver.getProvidersMetadata (http://192.168.0.24:8100/build/js/app.bundle.js:14603:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://192.168.0.24:8100/build/js/app.bundle.js:14412:34)
    at RuntimeCompiler.resolveComponent (http://192.168.0.24:8100/build/js/app.bundle.js:18308:47)
    at Tab.NavController.loadPage (http://192.168.0.24:8100/build/js/app.bundle.js:55441:24)
    at Tab.loadPage (http://192.168.0.24:8100/build/js/app.bundle.js:66776:35)
ERROR CONTEXT:
[object Object], http://192.168.0.24:8100/build/js/zone.js, Line: 260
`

**Comment by nraboy** [comment]
I tested all the providers just now and they work fine.  **192.168.0.24:8100** leads me to believe you're trying to use Ionic Serve or Ionic View.  Neither of those are compatible.

Best,
